"""
Loads the sycophancy experiment's question bank.

The actual data lives in data/questions.json, generated by data/build_dataset.py
from camilablank/sycophancy-datasets (Hugging Face). See that file's docstring
for why we only reuse the (question, choices, gold answer) from the raw
dataset and discard everything else.

Each item is a multiple-choice question (A-D) with:
- a neutral prompt (just the question)
- a biased prompt (a confident-authority persona asserting a specific wrong
  letter first, then the same question)
- a gold answer letter, short and unambiguous enough to string-match
"""

import json
from dataclasses import dataclass
from pathlib import Path

_DATA_PATH = Path(__file__).parent / "questions.json"


@dataclass
class QAItem:
    id: str
    question: str          # neutral prompt: the bare MCQ text
    biased_prompt: str      # precomputed persona + wrong-answer + MCQ text
    correct_answer: str     # gold letter, e.g. "B"
    wrong_answer: str        # pressured wrong letter, e.g. "C"
    authority_persona: str


def _load() -> list[QAItem]:
    with open(_DATA_PATH) as f:
        raw = json.load(f)
    return [
        QAItem(
            id=r["id"],
            question=r["neutral_prompt"],
            biased_prompt=r["biased_prompt"],
            correct_answer=r["correct_answer"],
            wrong_answer=r["wrong_answer"],
            authority_persona=r["authority_persona"],
        )
        for r in raw
    ]


QUESTION_BANK: list[QAItem] = _load()


def build_prompt(item: QAItem, biased: bool) -> str:
    return item.biased_prompt if biased else item.question


if __name__ == "__main__":
    for item in QUESTION_BANK:
        assert item.correct_answer != item.wrong_answer
        assert len(item.correct_answer) == 1

    print(f"{len(QUESTION_BANK)} questions loaded.")
    print("\nExample neutral prompt:")
    print(" ", build_prompt(QUESTION_BANK[0], biased=False))
    print("\nExample biased prompt:")
    print(" ", build_prompt(QUESTION_BANK[0], biased=True))
